import type { Role } from "@/generated/prisma/enums";

/**
 * Central permission map: role -> allowed actions.
 * Superset of the legacy per-module role checks.
 */
export const PERMISSIONS: Record<Role, string[]> = {
  SUPER_ADMIN: ["*"],
  ADMIN_OPERASIONAL: [
    "employee:read",
    "employee:write",
    "client:read",
    "client:write",
    "produk:read",
    "produk:write",
    "jadwal:read",
    "jadwal:write",
    "absensi:read",
    "absensi:write",
    "lembur:read",
    "lembur:approve",
    "izin:read",
    "izin:approve",
    "approval:read",
    "approval:process",
    "operations:read",
    "operations:write",
    "incident:read",
    "incident:write",
    "payroll:read",
    "payroll:write",
    "tiering:write",
    "viewdata:read",
    "history:read",
    "penilaian:write",
    "tukarshift:approve",
  ],
  CLIENT: [
    "client:read",
    "client:write",
    "produk:read",
    "produk:write",
    "jadwal:read",
    "jadwal:propose", // clients propose, ops approves
    "approval:read",
    "marketplace:read",
    "shortlist:read",
    "shortlist:write",
  ],
  CLIENT_ADMIN: [
    "client:read",
    "client:write",
    "produk:read",
    "produk:write",
    "jadwal:read",
    "jadwal:propose",
    "approval:read",
    "approval:process",
    "finance:read",
    "kpi:read",
    "marketplace:read",
    "marketplace:write",
    "shortlist:read",
    "shortlist:write",
  ],
  STREAMER: [
    "jadwal:read",
    "absensi:read",
    "absensi:write",
    "lembur:read",
    "izin:read",
    "suara:write",
    "tukarshift:read",
    "tukarshift:write",
    "penilaian:read",
    "lms:read",
    "lms:enroll",
    "qc:read",
    "marketplace:read",
    "marketplace:apply",
    "streamerprofile:write",
  ],
  STAFF: [
    "absensi:read",
    "absensi:write",
    "lembur:read",
    "izin:read",
    "suara:write",
    "penilaian:read",
  ],
  OTS: [
    "absensi:read",
    "absensi:write",
    "lembur:read",
    "izin:read",
    "suara:write",
  ],
  OPERATION: [
    "employee:read",
    "employee:write",
    "client:read",
    "client:write",
    "produk:read",
    "produk:write",
    "jadwal:read",
    "jadwal:write",
    "absensi:read",
    "absensi:write",
    "operations:read",
    "operations:write",
    "incident:read",
    "incident:write",
    "history:read",
  ],
  TRAINER: [
    "lms:read",
    "lms:write",
    "lms:grade",
    "lms:certify",
    "employee:read",
    "client:read",
  ],
  QC_MANAGER: [
    "qc:read",
    "qc:write",
    "qc:rubric",
    "qc:reports",
    "jadwal:read",
    "employee:read",
  ],
  QC_REVIEWER: [
    "qc:read",
    "qc:review",
    "jadwal:read",
    "employee:read",
  ],
  FINANCE: [
    "payroll:read",
    "payroll:write",
    "payout:read",
    "payout:write",
    "billing:read",
    "billing:write",
    "pnl:read",
    "client:read",
  ],
  FINANCE_MANAGER: [
    "payroll:read",
    "payroll:write",
    "payroll:approve",
    "payout:read",
    "payout:write",
    "payout:approve",
    "billing:read",
    "billing:write",
    "billing:approve",
    "pnl:read",
    "tiering:write",
    "client:read",
  ],
};

/**
 * Check whether a role has a permission (SUPER_ADMIN has all).
 */
export function hasPermission(role: Role, permission: string): boolean {
  const perms = PERMISSIONS[role];
  if (!perms) return false;
  if (perms.includes("*")) return true;
  return perms.includes(permission);
}
